#!/usr/bin/env python3

import os, shutil
from os.path import expanduser
home = expanduser("~")
theme = "thorsten-custom"


if __name__ == "__main__":
  shutil.copy2("Themes/for-gerry.zsh-theme", home + "/.oh-my-zsh/custom/themes")
  shutil.copy2("Themes/thorsten-custom.zsh-theme", home + "/.oh-my-zsh/custom/themes")
  shutil.copy2("history_command.zsh", home + "/.oh-my-zsh/custom")
  try:
    shutil.copytree("plugins/cmd", home + "/.oh-my-zsh/custom/plugins/cmd")
  except FileExistsError:
    shutil.copy2("plugins/cmd/cmd.plugin.zsh", home + "/.oh-my-zsh/custom/plugins/cmd")

  with open(home + "/.zshrc", "r") as f:
    lines = f.readlines()
    plugins = ['git', 'jump', 'svn', 'virtualenv', 'cmd']
    for index, line in enumerate(lines):
      if line.startswith("#"):
        continue
      if line.find("ZSH_THEME=") != -1:
        lines[index] = "ZSH_THEME=\"" + theme + "\"\n"
      if line.find("plugins=(") != -1:
        start = line.find("(")
        end = line.find(")")
        original_plugins = line[start+1: end].split(" ")
        additionals = list(set(original_plugins) - set(plugins))
        lst = plugins + additionals
        try:
          lst.remove('')
        except ValueError:
          pass
        lines[index] = "plugins=(" + " ".join(lst) + ")\n"
  with open(home + "/.zshrc", "w") as output:
    output.writelines(lines)

    